### ISSUE TITLE
Create a spot to store config.json in a centralized location on AWS

### ISSUE THREAD

**Issue by bryan-harter** [IMAP-Science-Operations-Center/sds-data-manager#1]
I was thinking a tiny dynamoDB table that all services can read, but if we already have an opensearch cluster, maybe theres a spot on opensearch where we can put these config files?

**Comment by bryan-harter** [comment]
In theory we could also just plop this config.json file into an S3 bucket upon stack creation too?

**Comment by sdhoyt** [comment]
We can create a new index in our existing OpenSearch instance (I think an index is analogous to a database) and store it there. It might be kind of a waste since you don't need good search for a single config, but it should be easy to do with OpenSearch.

**Comment by bryan-harter** [comment]
Yeah a new index inside opensearch sounds fine to me.  Before you start working on the ticket though, it might be worthwhile to update the config file to actually use the real filenames that we're expecting (I literally just made up the stuff in that config file for testing: 

https://lasp.colorado.edu/galaxy/display/IMAP/IMAP+SDC+to+Instrument+Team+ICD#IMAPSDCtoInstrumentTeamICD-1.4FileNamingConventions
