### ISSUE TITLE
Create Java Wrapper to the Upload/Query/Download APIs

### ISSUE THREAD

**Issue by bryan-harter** [IMAP-Science-Operations-Center/sds-data-manager#10]
Once we've finished all previous tickets before this (https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/1, https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/2, https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/3, https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/4, https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/5, https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/6, https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/7), we should make a JAVA wrapper to help with the various APIs.

See for example the EMM python/IDL scripts on this page: https://sdc.emiratesmarsmission.ae/software

The issue I see is I'm not sure how these scripts would avoid having to hard-code in the API Gateway endpoints and the cognito login. It seems like it should be able to retrieve them dynamically somehow. Maybe after deploying the CDK code, the app.py takes the output of the things that were generated and inserts them into a config file? Or sets environment variables at the top of the scripts or something?

The idea behind these scripts is that they are a single file that we could hand a scientist and say "here, you can download files to your local machine with the command download_sds_files(instrument=glows,level=l1a) or something.

**Comment by greglucas** [comment]
I don't think we need to make "download interfaces" for every language. If we have well-defined APIs, external users can use their favorite scripts and libraries to make these themselves. I would also argue to close this one.

**Comment by bryan-harter** [comment]
Yeah this one was just a special request from one of the scientists, it wasn't necessary but it would be nice of us.  I'm not sure what their comfort level with Java programming is and how well they could authenticate and perform HTTP requests on APIs is

**Comment by bryan-harter** [comment]
Regardless of what we decide to do here, it should live in the sds-access-lib repo if anything, so I'll close this
