### ISSUE TITLE
Document API endpoints

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/sds-data-manager#100]
**Summary**
Document the API endpoints described in #85, ideally with an automated tool such as OpenAPI/swagger

**Requirements**
TBD

**Related tickets*
- #85

**Comment by bourque** [comment]
It looks like this is relatively straightforward to make with SwaggerUI / SwaggerHub (https://swagger.io/tools/swaggerhub/).  I'll get working on it!

**Comment by bourque** [comment]
I would only call this a first draft, as there are likely some mistakes in here and probably some missing parameters, but I am hoping this will get us by for now for SIT2:

[imap_sdc_api.pdf](https://github.com/IMAP-Science-Operations-Center/sds-data-manager/files/12296656/imap_sdc_api.pdf)

I also have an HTML file of this (which is much nicer to look at), but GitHub does not allow HTML files to be uploaded here.

It is also available here (for now): https://app.swaggerhub.com/apis/MATTHEWBOURQUE/test_api/1.0.0

**Comment by bryan-harter** [comment]
That looks cool!

On the upload API, we shouldn't need the parameter "remote_filename".  That's the purpose of the regular (required) "filename" parameter.  If you noticed that it was sending the remote_filename parameter, that's probably an error with the script, I believe it sends all the arguments to the function as query parameters.  It doesn't hurt anything, but it also doesn't do anything.

**Comment by bourque** [comment]
We now have a documentation page for this! https://imap-processing.readthedocs.io/en/latest/data-access-api/index.html
