### ISSUE TITLE
SPICE Processing

### ISSUE THREAD

**Issue by laspsandoval** [IMAP-Science-Operations-Center/sds-data-manager#116]
### Requirements:

> **Specify:  **
We need to create processing code for SPICE. This will be reviewed at the meeting with Scott Turner at APL.

### Algorithm Code Information:
> Input data:
> > **Specify details:**
>
> Algorithm steps/psuedocode:
> > **Specify details:**
>
> Output data:
> > **Specify details:**

### Code:

```python
# Code
```

**Comment by laspsandoval** [comment]
This needs to be moved to sds-data-manager since it is more of an architecture issue.

**Comment by greglucas** [comment]
FYI there is a transfer issue link in the bottom right of an issue that you can use so you can bring the comments and labels along too.
![image](https://github.com/IMAP-Science-Operations-Center/sds-data-manager/assets/12417828/c41c7427-935b-4971-b1fc-434a5ed31abb)
