### ISSUE TITLE
Create API metrics Dashboard

### ISSUE THREAD

**Issue by tech3371** [IMAP-Science-Operations-Center/sds-data-manager#130]
This issue is an outcome from SIT-2 review. We didn't have metrics Dashboard to demonstrate data transfer (SIT-2 document and section 5.3.3). Should we create API metrics Dashboard through CDK?

**Comment by bryan-harter** [comment]
Maybe a SPIKE to discuss how we want to monitor the APIs?

**Comment by tech3371** [comment]
This is what was required from SIT-2
```
Navigate to CloudWatch and click on "metrics", showing the API requests and data transfer amounts
```
After doing some research, this dashboard is already exist and provided by AWS. We don't need to create it.


![Image](https://github.com/IMAP-Science-Operations-Center/sds-data-manager/assets/36522642/29558799-0089-440a-9cfc-e486850d3024)

**Comment by tech3371** [comment]
Link to SIT-2: https://lasp.colorado.edu/galaxy/display/IMAP/SDC-SIT-2
