### ISSUE TITLE
SPIKE - Processing infrastucture and priorities part #2

### ISSUE THREAD

**Issue by laspsandoval** [IMAP-Science-Operations-Center/sds-data-manager#153]
## Description

Take the design from #74 and create cdk code. Create scenarios to see if the design works as expected. 

## Requirements
- Requirement 1
- Requirement 2

### Nice to have or Goal Requirements
- Nice to have 1
- Nice to have 2

## Additional notes
Any additional notes on the issue, if you have them. 

## Related tickets
- #68 
- #71
- #72
- #74 

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- [ ] Placeholder ticket

**Below is the template for the response to this ticket. Add as many solutions as needed, but preferably include 2-5 for discussion. The response should be posted as a comment on this issue, or linked in a comment. **

# Solution 1
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Solution 2
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Summary
Write up a summary of your findings, including your preferred solution.

**Comment by maxinelasp** [comment]
Is this complete with your spike #154 @laspsandoval ? Would it be possible for you to write up the results of that investigation in a comment here? It seems like you didn't run into any major issues with the design we have, so maybe you can create a follow up ticket and close this spike. Or, if there are still unanswered questions, it would be good to know what those are here.

**Comment by sdhoyt** [comment]
Closing SPIKE based on work done in #154.
