### ISSUE TITLE
Create a processing fail path that every instrument can use in their processing pipeline

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/sds-data-manager#172]
### Summary
Describes how SNS could be used.

Setup SNS topic using EventBridge.
https://lasp.colorado.edu/galaxy/display/IMAP/IMAP+EventBridge+Rules

### Requirements

The more specific the better.
  - [ ]
  - [ ]

**Comment by laspsandoval** [comment]
Duplicate ticket
