### ISSUE TITLE
Check if there is job already in progress before kicking off new batch job

### ISSUE THREAD

**Issue by tech3371** [IMAP-Science-Operations-Center/sds-data-manager#293]
It may kicks off duplicate batch job when we ingests two files that is upstreams dependency certain downstream data level and product. Gg. two l1a files ingest could kicks off two same l1b batch job because we have not added checks if certain job has been kicked off or not.

**Comment by greglucas** [comment]
This is implemented by checking the database whether a job is INPROGRESS or SUCCESSFUL, so I believe can be closed.
xref: https://github.com/IMAP-Science-Operations-Center/sds-data-manager/pull/309
