### ISSUE TITLE
BUG - Deploy for I-ALiRT failing

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/sds-data-manager#317]
### Description of the issue

When trying to deploy, some of the I-ALiRT components are failing to deploy. This blocks automatic deploy from Github and requires some manual intervention to deploy

### Steps to reproduce the issue

Just run an automatic deploy, or look at the deploy from my last PR [here](https://github.com/IMAP-Science-Operations-Center/sds-data-manager/actions/runs/10102189191)

### Expected behavior (What should happen)

Deploy should succeed

### Actual behavior (What does happen)

Deploy fails due to timeout on IalirtServiceSecondary deploy step. To get around this, I needed to deploy the stacks manually.

### Code Snippet:

```python
Code
```

### Additional notes, affected areas, and suggested fixes

I would prefer to make I-ALiRT a separate deployment - this would keep both projects separate, and prevent issues from IMAP processing from affecting I-ALiRT deployment and vis-versa. No need to tie the two pieces together unnecessarily.

**Comment by laspsandoval** [comment]
![Screenshot 2024-08-21 at 11 38 56 AM](https://github.com/user-attachments/assets/559cd407-1e9d-456a-953b-aa34e8f0a568)

**Comment by laspsandoval** [comment]
It is now deployed. I have to make certain the I-ALiRT ECR is populated w/ the most current test containers. That was the fix.

**Comment by greglucas** [comment]
I'm going to reopen this to discuss because an ECR shouldn't need to be populated for a deploy to work IMO, or if it is required, we should have a build step to do that ECR push. Can you comment on exactly why we need a "test" container, or where that is failing in the code?

**Comment by maxinelasp** [comment]
Possibly related question to Greg's - if we were to destroy the entire environment and then rebuild, would your fix continue to work? Or would the deploy fail because there isn't a test container?
