### ISSUE TITLE
Move project to poetry

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/sds-data-manager#37]
We should move the project away from pip and setup tools to poetry in order to standardize dependency management and use a more powerful dependency management tool to fix some of the pip issues we saw in the SIT-1 test. 

Poetry also creates a project-specific virtual environment and manages tests and packaging. It allows for optional dependencies. We can export the poetry project to a requirements.txt if required for lambda.

**Comment by greglucas** [comment]
Closed by #38
