### ISSUE TITLE
Create an API that would be able to handle admin tasks

### ISSUE THREAD

**Issue by bryan-harter** [IMAP-Science-Operations-Center/sds-data-manager#5]
The only admin task I can think of at the moment is adding a new data file type to the SDS, so maybe it would sync the local config.json file to wherever central location of the config.json ends up (see ticket the https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/issues/1)

**Comment by greglucas** [comment]
Closing this as I think we decided not to have this in API form. Feel free to reopen if you disagree.
