### ISSUE TITLE
SPIKE: Create a file backup system

### ISSUE THREAD

**Issue by bryan-harter** [IMAP-Science-Operations-Center/sds-data-manager#53]
We'll need to make a script to sync a data bucket from the production account to the backup account.  This will probably be its own CDK stack, maybe even a separate repository? 

I envision a simple batch job that syncs data from one bucket to another, perhaps putting the data into glacier.  This batch job would live on the backup account, and read from the primary IMAP bucket.

**Comment by greglucas** [comment]
Do we only need to back up the data, or are you looking to back up other services as well?

Batch doesn't seem like the right solution to me... We should discuss what LASP's Cloud Working Group is doing for backups so we can standardize the approach across projects. I think LASP was looking at doing some backups in AWS, but that might have been for `on-prem -> cloud` which I'm guessing is a different approach than `cloud -> cloud`

Seems like we should really just replicate data if it is an s3 bucket that just needs to be duplicated:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html

Or use AWS-backup: https://docs.aws.amazon.com/aws-backup/latest/devguide/s3-backups.html
https://docs.aws.amazon.com/aws-backup/latest/devguide/create-cross-account-backup.html

Setting up s3 permissions between accounts: https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/copy-data-from-an-s3-bucket-to-another-account-and-region-by-using-the-aws-cli.html

**Comment by maxinelasp** [comment]
# S3 Replication:
Data can be replicated from one bucket into another, including across accounts. This data can be replicated in a streaming way or in batch. 

## Pros:
- Easy to set up
- automatic
- Can replicate to different accounts
- Keeps metadata
- Can replicate into glacier, or to normal S3 with a timer to move to glacier
- Can work with batch or with streaming
- Can replicate subsets of objects

## Cons:
- More difficult to track replication
- Only s3
- Needs setup in both accounts

# AWS backup
Backup system for storing data out of S3 or databases into a "Backup Vault." The data can be stored for a given amount of time, including indefinitely. It is easy to restore the data. 

## Pros:
- Can backup other services like databases, storage, and compute
- Backups go to one location (Backup vault)
- Operates same way for S3 backups as S3 replication 
- periodic backups can be retained for any amount of time
- incremental backups
- On demand backups and scheduled backups
- Can easily restore

## Cons:
- Glacier not fully supported
- Cannot transition into glacier after a certain amount of time
- Data is in a backup vault, not a different account (different accounts can access the vault)

# Custom solution
We could create a system that processes files as they are created or uploaded, and manage all backups manually (potentially using S3 replication as a backend)

## Pros:
- Fully custom solution
- Backups would be integrated into the file manager 
- All info about files would be captured in one place
- Could use S3 replication or AWS backup in a very fine tuned way

## Cons:
- more work
- more fragile
- All advantages might be able to be captured out of S3 replication or AWS backup
- We don't have a design or idea what the data manager will look like, so we might end up with work we don't use

# Summary
In my opinion, either S3 replication or AWS Backup would work well for this case. In the case of S3 buckets, I think S3 replication will work just fine, and we can set up something to move the other account's data into glacier after a short amount of time. This would protect us against getting locked out of the production account or data loss. 

AWS Backup is probably overkill for what we need here, but it would be good to keep in mind for future usecases. We could consider using that to back up the last 30 days of data, eg, and use either glacier or some non-AWS solution for more catastrophic data loss (such as the SPDF archive.) In particular, AWS Backup is worth keeping in mind for databases or other processes, even if it's not needed for S3 files. 

@greglucas @sdhoyt @tech3371

**Comment by greglucas** [comment]
:+1: Excellent summary! It sounds like S3 replication is probably the place to start and we can always expand to the other options later if we need to backup compute or additional metadata etc... Some additional questions you'll want to think about while implementing it are which account do we want to implement this in and do we want to control any of this via CDK or just document really well what was done?

**Comment by maxinelasp** [comment]
> 👍 Excellent summary! It sounds like S3 replication is probably the place to start and we can always expand to the other options later if we need to backup compute or additional metadata etc... Some additional questions you'll want to think about while implementing it are which account do we want to implement this in and do we want to control any of this via CDK or just document really well what was done?

I agree. We will need to have something in both accounts for S3 replication. It looks like it's just a JSON file to set it up - so if we're creating/maintaining the buckets with CDK, my guess is that it will be easy to add this part of it as well.

**Comment by tech3371** [comment]
I agree. S3 replication is what I would have gone for too. But good to know we can backup few other services using AWS backup. I didn't know about AWS backup was a thing.

If we want to setup S3 replication through CDK, this link might be helpful, https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_s3/CfnBucket.html.

**Comment by maxinelasp** [comment]
Yes, that looks exactly right. Do we have any buckets set up in CDK now? 

AWS backup is definitely interesting, in my opinion, it would be good to back up everything and store it for a few days, so we can restore if something goes really wrong. But that's for another time!

**Comment by tech3371** [comment]
We create a bucket in `sds-data-manager` repo and under this folder `sds_data_manager/sds_data_manager_stack.py`.

I totally agree.

**Comment by maxinelasp** [comment]
Created new ticket #67  to track this work, so I am marking the spike complete.
