### ISSUE TITLE
SPIKE - Investigate how to set up a base domain name

### ISSUE THREAD

**Issue by greglucas** [IMAP-Science-Operations-Center/sds-data-manager#65]
## Description

We want to set up a base domain name for the project so that we can attach all of our routes in the CDK to it rather than having to point users at a long unrecognizable url `123.aws-service.us-east.blah`.

## Requirements
- Give the team a few domain name options to vote on.
- Decide which account the domain should live in. (Do we buy it from backup, dev, or prod and share certificates or is there something else to do)
- Investigate which pieces should live in the CDK vs CLI vs Console

### Nice to have or Goal Requirements
- It would be nice to have `dev.domain.com` as a subdomain that we can use on our dev account. (In SWx TREC we have `dev.domain.com` and `prod.domain.com` and then have some kind of routing from `prod.domain.com` -> `domain.com` so that the prod doesn't get displayed I believe.
- Investigate certificates and where/how we should be maintaining those on the project.

## Additional notes

I think @bryan-harter said he set up EMM's routing, and @bmcclellan-cu set up SWx TREC's, so one of you probably wants to investigate this and give the team your ideas on what approach we should take.

## Related tickets
- `#123` 

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- [ ] Placeholder ticket

**Below is the template for the response to this ticket. Add as many solutions as needed, but preferably include 2-5 for discussion. The response should be posted as a comment on this issue, or linked in a comment. **

# Solution 1
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Solution 2
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Summary
Write up a summary of your findings, including your preferred solution.

**Comment by bryan-harter** [comment]
This one is complete, right @greglucas ?

**Comment by greglucas** [comment]
Yes, closed by https://github.com/IMAP-Science-Operations-Center/sds-data-manager/pull/102
