### ISSUE TITLE
SPIKE - Infra design 1: file data and initial data flow

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/sds-data-manager#71]
## Description

This spike should determine what the data flow looks like for the overall system, with a particular focus on what occurs after data lands in the IMAP S3 bucket. This should include a design for updating the metadata and processing databases and triggering processing. This does not need to  make final decisions for specific technologies to use, but should include pros and cons for different AWS services - in particular, SQS and SNS vs EventBridge. 

This spike is building off discussions from #68.

## Requirements
- Include information on system triggers and what information is passed around
- There should be a way to export information to multiple systems (eg the processing database and the metadata opensearch)
- This spike should build off of our previous discussions and address the concerns brought up earlier

### Nice to have or Goal Requirements
- Discussion on how to manage large bursts of data every 3-4 days
- For each solution, include how processing is triggered, but don't worry about what exactly the processing looks like
- A diagram similar to #68 for each main design
- At least: an event driven design, and a batched design, to compare the two 

## Additional notes
Some additional concerns:
- Do we wait for all the data to arrive, and process last-second, or process as we get it and potentially miss some?
- Discuss and decide between flexibility, reliability, and simplicity. In general, do we prefer solutions to be flexible? or reliable? 
- You should note if a particular design choice eliminates complexity, or if it pushes it somewhere else in the system.

## Existing design
You can expand on this design, or discard it.
The design proposed in #68 was an SQS queue which would trigger upon files landing in S3. This SQS queue would get copied into three locations: the processing data updater, to create rows in a database, the metadata opensearch updater, to create the file metadata, and the processing, which would trigger the processing for each file. 

## Related tickets
- #68 
- #72 
- #97 
- #153 

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- [ ] Placeholder ticket

**Below is the template for the response to this ticket. Add as many solutions as needed, but preferably include 2-5 for discussion. The response should be posted as a comment on this issue, or linked in a comment. **

# Solution 1
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Solution 2
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Summary
Write up a summary of your findings, including your preferred solution.

**Comment by tech3371** [comment]
I can take this spike

**Comment by maxinelasp** [comment]
Completed with this [document](https://lasp.colorado.edu/galaxy/display/IMAP/SDC+Processing+Architecture+Overview) by @laspsandoval. 

Follow up tickets:
#153 
#72 (for what the database tables will actually look like)
#97
