### ISSUE TITLE
SPIKE - Infra design 3: Data watcher and API

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/sds-data-manager#73]
## Description

This spike should explore if we would like to create a system for tracking data processing, and what that system might look like. This could include an API for external access. This will build off of ticket #72, but you can assume that any data the system needs is possible to retrieve and focus on the external access. 

## Requirements
- The system should provide a way to check the status of a given file or data source

### Nice to have or Goal Requirements
- Some way to track an overview of the entire system
- Examples of the kinds of overall monitoring on data processing - may not stem from the data watcher, but it could

## Additional notes
This might be useful for external stakeholders, so keep in mind that some outside of LASP access might be required. This system might be closely related to the system for uploading files into AWS. 

## Existing design
The existing design is a simple Lambda, with presumably some kind of fairly standard API gateway connection on the other side. This lambda would read from a database containing file tracking data.

## Related tickets
- #68 
- #71 
- #61 
- #47 

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- [ ] Placeholder ticket

**Below is the template for the response to this ticket. Add as many solutions as needed, but preferably include 2-5 for discussion. The response should be posted as a comment on this issue, or linked in a comment. **

# Solution 1
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Solution 2
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Summary
Write up a summary of your findings, including your preferred solution.

**Comment by bourque** [comment]
I can look into this one

**Comment by maxinelasp** [comment]
This is closely related to our discussion about user stories: https://lasp.colorado.edu/galaxy/display/IMAP/User+Stories 

Right now, it's looking like this will not be needed, but as that's still somewhat in the air, I'm going to leave this spike open. This spike should describe what kind of data tracking internal and external users might want to see, to determine if that's something that can be accomplished with a metadata database + cloudwatch metrics, or if we do want some kind of dependency table or processing status tracking table (#86 #105 )

**Comment by maxinelasp** [comment]
Covered by RDS for now
