### ISSUE TITLE
Change logs to use string formatter 

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/sds-data-manager#75]
Some of the logs are using string concatenation and should be updated to using string formatting.

String formatting example:
```python
logger.info("Query: %s" % query.query_dsl())
```

String concatenation example:
```python
logger.info("Query: " + str(query.query_dsl())
```

**Comment by bourque** [comment]
I looked through the logging statements in the repository and it looks like none of them are using string concatenation anymore, so I think this can be closed.
