### ISSUE TITLE
SPIKE - OpenSearch Back-up

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/sds-data-manager#76]
## Description
We want to have a way to back-up/restore metadata stored in our OpenSearch instance.

## Requirements
- Investigate what options are available for backing-up OpenSearch

## Related tickets
- #53 

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- [x] #98 
- [x] #99

**Comment by sdhoyt** [comment]
# Solution 1: OptionSearch Service Manual Snapshots
OpenSearch Service Manual Snaspshots can be used for cluster recovery or for moving data from one cluster to another. The opensearchpy API can be used to create the snapshot after each new set of data is indexed into OpenSearch. There's no limit to Snapshot storage. The S3 bucket can be backed-up into another account
 
## Pros:
- Can all be done in cdk
- Data snapshots could be backed up to a separate account in an S3 bucket
- Brian McClellan already has some code that does this
 
## Cons:
- May be more work to write/test/maintain code as opposed to solution 2
 
 
# Solution 2: Automated Snapshots with OpenSearch Snapshot Management
OpenSearch Service Snapshot Management is a way to automate snapshot creation within the opensearch instance. The version of OpenSearch we're using in the cdk does not have this capability. We would need to upgrade to version 2.3. In version 2.3 you can setup Snapshot Management in the OpenSearch dashboard.
 
## Pros:
- Can be setup in OpenSearch Dashboards
- Can create a snapshot policy and customize how often and when snapshots are taken and how long to retain the snapshots (default is retain forever)
 
## Cons:
- Can only be setup with REST API or Dashboard (no cdk)
- The snapshot can't be backed-up in a separate account, it would all be handled on the main account.
 
 
# Solution 3: Do Nothing
The S3 bucket containing the data is backed-up in a separate account and can be re-indexed into OpenSearch if needed.
 
## Pros:
- No additional work
- Re-indexing all the data shouldn't take too long. When I was testing out OpenSearch, I indexed all of the EMM data in minutes and this would only happen if we needed to restore the cluster using the backup data.
 
## Cons:
- Would lose any information we have showing mismatches between our stored metadata and stored data that may have occurred.
- If we want to use OpenSearch to index any other kind of data that can't be easily re-indexed from an S3, then we wouldn't have a backup.
 
# Summary
 
I think solution 1 is the best choice for all the reasons stated above. Solution 2 may be easier in some ways, but I spent a lot of time trying to find consistency in different parts of the documentation and wasn't ever able to get the option to even appear in my dashboard. Solution 3 may also be fine, but if we want to use OpenSearch for any other storage, this won't be usable.

**Comment by GFMoraga** [comment]
Input:
I looked into options 1 and 2, and it seems that they can occur at the same time. I do not know the difference in cost, but it could be something worth looking into if we can get the best of both worlds. 

O1: This seems to be the most cost-efficient. I want to say that it can be run with cdk, or at least the CLI in AWS.  I think the flexibility and specification are great! 
O2: If this backup is internal only, then O1 is the way to go. However, we could use an internal and a separate one for the manual snaps. This could get too complex if we are trying to keep it simple. 
O3: This option could save $, but it is a hassle to re-index when needed. What else would OpenSearch be used for?

**Comment by greglucas** [comment]
I think option 1 sounds like a good path forward from what you described. I doubt the maintenance would be too terrible since we shouldn't be touching it all that often. It sounds like Option 2 is newer, so if it does progress and become a better option (like CDK integration) I don't see an issue with switching over to that in the future if we want, but no point in wasting your time on that approach now especially if it was somewhat confusing already.

**Comment by bourque** [comment]
I just wanted to note that I reviewed what was written here and I agree that options 1 and 2 both sound good, with option 1 being slightly better.  But this is based on my very limited knowledge of OpenSearch and cdk 😅
