### ISSUE TITLE
Write API to upload data

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/sds-data-manager#84]
**Summary**
An API needs to be written to upload data to the data storage bucket

**Parent Requirement**

SOC-SDC-L4-59 | Data Access API | The SDC shall make available an API, available to both the IMAP science team and general public, that enables automated data access. | Requirement | Necessary to support dissemination of science data to the global heliophysics community. | SOC-L3-57 | Test
-- | -- | -- | -- | -- | -- | --

**Comment by bryan-harter** [comment]
This was finished!
