### ISSUE TITLE
Create API Endpoint

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/sds-data-manager#85]
**Summary**
An API Endpoint should be created to handle API upload, query, download requests

**Parent Requirement**

SOC-SDC-L4-59 | Data Access API | The SDC shall make available an API, available to both the IMAP science team and general public, that enables automated data access. | Requirement | Necessary to support dissemination of science data to the global heliophysics community. | SOC-L3-57 | Test | SIT-1: Query, Download API in pythonSIT-2 | SIT-2
-- | -- | -- | -- | -- | -- | -- | -- | --

**Tasks**
- [ ] #79 
- [x] #100

**Comment by bourque** [comment]
I believe #100 is 'done' enough for SIT-2, though I would like to make future improvements.

**Comment by bryan-harter** [comment]
This one is completed by #102
