### ISSUE TITLE
Create a Backup AWS Account

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/sds-data-manager#91]
**Summary**
A Backup AWS Account should be setup to allow for a complete copy of the SDC to be stored to recover from a catastrophic failure resulting in data loss of the main account

**Parent Requirement**
SOC-SDC-L4-73 | Off-Site Data Storage | The SDC shall be capable of storing a complete copy of itself in a secure off-site data repository in order to recover from catastrophic events resulting in data loss. | Requirement | Necessary to perform science processsing and analysis. | SOC-L3-2 | Test
-- | -- | -- | -- | -- | -- | --

**Comment by bryan-harter** [comment]
Would this be considered complete when the account is created, or when the backups are working?

**Comment by sdhoyt** [comment]
@bryan-harter This can be closed when the account is created
