### ISSUE TITLE
SPIKE - Track Data Availability

### ISSUE THREAD

**Issue by tech3371** [IMAP-Science-Operations-Center/sds-data-manager#95]
## Description

Short description of the issue you would like to solve. 

## Requirements
- Requirement 1
- Requirement 2

### Nice to have or Goal Requirements
- Nice to have 1
- Nice to have 2

## Additional notes
Any additional notes on the issue, if you have them. 

## Related tickets
- `#123` 

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- [x] #105 

**Below is the template for the response to this ticket. Add as many solutions as needed, but preferably include 2-5 for discussion. The response should be posted as a comment on this issue, or linked in a comment. **

# Solution 1
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Solution 2
Write an overview of the solution here.

## Pros:
- pro 1

## Cons:
- con 1

## Additional notes:
- note

# Summary
Write up a summary of your findings, including your preferred solution.

**Comment by maxinelasp** [comment]
MAG will trigger reprocessing for other instruments after they upload a file and we generate the official L2 MAG file (~1 month after first processing). It would be good to track dependencies across the project so we can know when to trigger new jobs - and it would be good to trace processing jobs or files back to the trigger point (So, when reprocessing some instrument L3, it would be good to point back to the MAG L2 as a trigger for reprocessing).

**Comment by maxinelasp** [comment]
Per our [discussions on databases](https://lasp.colorado.edu/galaxy/pages/viewpage.action?spaceKey=IMAP&title=User+Stories), it doesn't look like we will need a data watcher specific database to achieve our requirements. 

Each processing step will use the metadata database to determine if all the data they need is available yet. Each processing step for every level on every instrument will have a lambda function which checks for dependent data availability using the metadata table (and some way of tracking spice and other ancillary files). 

For reprocessing/triggering, whenever a dependent file lands in S3, it should end up in eventbridge. This will trigger any dependent step functions (each eventbridge bus [knows what steps are triggered](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-bus.html)) Every step function will first check (with a lambda) if all the files required for that processing step are available. They will check using the metadata table. Therefore, the metadata processing table and the cloudwatch tracking processing are probably sufficient for tracking the data.
